### ISSUE TITLE
most recent call last

### ISSUE THREAD

**Issue by congaro75** [LazyDeveloperr/Lazy-Streamer-BOT#1]
run " python3 -m Adarsh" not work
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/haihn/Lazy-Streamer-BOT/Adarsh/__main__.py", line 10, in <module>
    from .bot import StreamBot
  File "/home/haihn/Lazy-Streamer-BOT/Adarsh/bot/__init__.py", line 4, in <module>
    from ..vars import Var
  File "/home/haihn/Lazy-Streamer-BOT/Adarsh/vars.py", line 10, in <module>
    class Var(object):
  File "/home/haihn/Lazy-Streamer-BOT/Adarsh/vars.py", line 12, in Var
    API_ID = int(getenv('API_ID'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by AshishYesale7** [comment]
If you are hosting it on VPS add one more file .env ad add all the variables to it .

**Comment by AshishYesale7** [comment]
> run " python3 -m Adarsh" not work
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/__main__.py", line 10, in <module>
>     from .bot import StreamBot
>   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/bot/__init__.py", line 4, in <module>
>     from ..vars import Var
>   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/vars.py", line 10, in <module>
>     class Var(object):
>   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/vars.py", line 12, in Var
>     API_ID = int(getenv('API_ID'))
> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> ```

If you are hosting it on VPS add one more file .env ad add all the variables to it .

**Comment by congaro75** [comment]
> > run " python3 -m Adarsh" not work
> > ```
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
> >     exec(code, run_globals)
> >   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/__main__.py", line 10, in <module>
> >     from .bot import StreamBot
> >   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/bot/__init__.py", line 4, in <module>
> >     from ..vars import Var
> >   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/vars.py", line 10, in <module>
> >     class Var(object):
> >   File "/home/haihn/Lazy-Streamer-BOT/Adarsh/vars.py", line 12, in Var
> >     API_ID = int(getenv('API_ID'))
> > TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> > ```
> 
> If you are hosting it on VPS add one more file .env ad add all the variables to it .

Thanks for replying to me.

Right from the beginning I created the config.env file and declared the APP ID, hash token information, but still got the same error as I said last time.



Now, I have declared the information directly in the file "Adarsh/vars.py"

When running the command "python3 -m Adarsh"

The bot was executed as follows

![image](https://github.com/LazyDeveloperr/Lazy-Streamer-BOT/assets/142249913/65ed2310-1ee9-48db-ab9e-f1576b160b2c)


I conduct bot test from telegram with command "/start"

However, the following error occurs

![image](https://github.com/LazyDeveloperr/Lazy-Streamer-BOT/assets/142249913/44d7ea37-eff8-48b5-ae54-478d1f839096)

Full log:

https://prnt.sc/Ke_dvG_pkhDL

Can you help me fix this?

Thank you very much.
